[package]
name = "protocol"
version = "0.1.1"
authors = ["Mubelotix <unbeliever.in.time@gmail.com>"]
edition = "2018"

[dependencies]
serde_yaml = "0.8"
getrandom = "0.1.13"
serde = { version= "1.0.103", features = ["derive"] }