[package]
name = "protocol"
version = "0.1.1"
authors = ["Mubelotix <unbeliever.in.time@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.0"
serde = { version= "1.0.103", features = ["derive"] }